version: "2.1"
services:

  eurekaserver:
    image: eurekaimg
    build: eureka/
#    restart: always
    network_mode: host
    container_name: eureka
    ports:
      - 8761:8761
    expose:
      - 8761
    healthcheck:
      test: "exit 0"


  configserver:
    image: configimg
    build: config-server/
#    restart: always
    network_mode: host
    container_name: config
    ports:
      - 8888:8888
    expose:
      - 8888
    healthcheck:
      test: "exit 0"


  zuulservice:
    image: zuulimg
    build: zuulapigateway/
#    restart: always
    network_mode: host
    container_name: zuul
    depends_on:
      - eurekaserver
      - configserver
    ports:
      - 8091:8091
    expose:
      - 8091
    healthcheck:
      test: "exit 0"


  mongoservice:
    image: mongo
    restart: always
    network_mode: host
    container_name: db
    ports:
      - 27017:27017
    healthcheck:
      test: "exit 0"

  muzixservice:
    image: muziximg
    build: muzix/
#    restart: always
    network_mode: host
    container_name: muzix
    depends_on:
      - eurekaserver
      - configserver
      - zuulservice
    ports:
      - 8080:8080
    expose:
      - 8080
    healthcheck:
      test: "exit 0"